name: CI Test and Coverage

on:
  push:
    branches:
      - test_branch  # Trigger on pushes to test_branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-html

      - name: Run Tests and Generate Coverage
        run: |
          coverage run -m pytest  # Run tests and collect coverage
          coverage report          # Output coverage in the terminal
          coverage html            # Generate HTML report

      - name: Check Coverage
        id: coverage-check
        run: |
          coverage_percentage=$(coverage report | tail -n 1 | awk '{print $4}' | sed 's/%//')
          echo "Coverage percentage: $coverage_percentage"
          echo "::set-output name=coverage_percentage::$coverage_percentage"
        shell: bash

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/index.html  # Path to the coverage HTML report

      - name: Comment on the pull request
        if: ${{ github.event_name == 'push' && steps.coverage-check.outputs.coverage_percentage != '' }}
        uses: actions/github-script@v6
        with:
          script: |
            const coverage = ${{ steps.coverage-check.outputs.coverage_percentage }};
            if (coverage >= 70) {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `All test cases passed and coverage is ${coverage}%.`
              });
            } else {
              github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Test cases failed or coverage is below 70%. Coverage: ${coverage}%.`
              });
            }
